const action_types = {
    ADD_USER: 'ADD_USER',
    SET_USER: 'SET_USER',
    LOGIN_USER: 'LOGIN_USER',
    SET_RESTAURANT: 'SET_RESTAURANT',
    SET_ORDERS: 'SET_ORDERS',
    SET_ORDER_DETAIL: 'SET_ORDER_DETAIL',
    SET_ITEM: 'SET_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    SET_MENU: 'SET_MENU',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS'
};

export default action_types;