const action_types = {
    ADD_USER: 'ADD_USER',
    SET_USER: 'SET_USER',
    LOGIN_USER: 'LOGIN_USER',
    SET_RESTAURANT: 'SET_RESTAURANT',
    SET_ORDERS: 'SET_ORDERS',
    SET_ORDER_DETAIL: 'SET_ORDER_DETAIL',
    SET_ITEM: 'SET_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    SET_MENU: 'SET_MENU',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_CUSTOMER_SELECTED_RESTAURANT: 'SET_CUSTOMER_SELECTED_RESTAURANT',
    ADD_TO_CART: 'ADD_TO_CART',
    SET_INVALID: 'SET_INVALID',
    CLEAR_CART: 'CLEAR_CART',
    SET_ITEM_IMAGE: 'SET_ITEM_IMAGE',
    SET_PROFILE_IMAGE: 'SET_PROFILE_IMAGE',
    SET_RESTAURANT_IMAGE: 'SET_RESTAURANT_IMAGE',
    PERSIST: 'persist/REHYDRATE'
};

export default action_types;